version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
   prometheus_data:
   grafana_data:

services:
   prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
       - prometheus_data:/prometheus
     networks:
       - aw-network
     ports:
       - 9090:9090
   grafana:
     image: grafana/grafana:latest
     ports:
       - 3001:3000
     networks:
       - aw-network