management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true

resilience4j.circuitbreaker:
  instances:
    avalicaoCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8
