name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
            
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Adicionando um est치gio de qualidade para garantir que o deploy s칩 ocorra se o c칩digo passar pela an치lise do SonarCloud
      - name: Check SonarCloud Quality Gate
        run: |
          STATUS=$(curl -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" \
            | jq -r .projectStatus.status)
          if [ "$STATUS" != "OK" ]; then
            echo "Quality gate failed: $STATUS"
            exit 1
          fi
